spring.application.name=REES-6


user.existsByEmail = SELECT COUNT(*) FROM users WHERE email = ?
user.existsByPhone = SELECT COUNT(*) FROM users WHERE phone = ?
user.insert = INSERT INTO users (user_id, email, password, name, phone, role, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
user.findByEmail = SELECT * FROM users WHERE email = ?
user.updatePassword = UPDATE users SET password = ? WHERE user_id = ?
UPDATE_PASSWORD=UPDATE User SET password = ? WHERE email = ?


#plot queries
plotinquirer.insert = INSERT INTO plot_inquirer (phone_number, name, address, created_at) VALUES (?, ?, ?, ?)

# SQL query to save a new project into the database
i# Project-related queries
project.selectAll=SELECT * FROM Project;
project.selectById=SELECT * FROM Project WHERE project_id = ?;
project.insert=INSERT INTO Project (project_name, survey_number, location, total_area, saleable_area, project_type, project_status, map_pdf) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
project.update=UPDATE Project SET project_name = ?, survey_number = ?, location = ?, total_area = ?, saleable_area = ?, project_type = ?, project_status = ?, map_pdf = ? WHERE project_id = ?;


plot.insert = INSERT INTO plot (project_id, site_number, status, size, facing, type, road_width, customer_id) VALUES (?, ?, 'available', ?, ?, ?, ?, NULL)

plot.update = UPDATE plot SET site_number = ?, size = ?, facing = ?, type = ?, road_width = ?, updated_at = CURRENT_TIMESTAMP WHERE plot_id = ?

plot.selectByStatusAndProject = SELECT * FROM plot WHERE status = ? AND project_id = ?
plot.selectByProject = SELECT * FROM plot WHERE project_id = ?
plot.selectById = SELECT * FROM plot WHERE plot_id = ?

# Customer Queries
customer.insert=INSERT INTO customer (name, address, contact_number, aadhaar_number, pan_number, created_at) VALUES (?, ?, ?, ?, ?, NOW())
customer.selectByPhone=SELECT * FROM customer WHERE contact_number = ?
customer.selectAll=SELECT * FROM customer ORDER BY created_at DESC



# --- Sales Related ---
sales.insert = INSERT INTO sales (project_id, plot_id, customer_id, amount_received, selling_price, created_at, mode_of_payment, description) VALUES (?, ?, ?, ?, ?, NOW(), ?, ?)

plot.selectAvailableByProject = SELECT * FROM plot WHERE project_id = ? AND status = 'available'

plot.updateStatusAndCustomer = UPDATE plot SET customer_id = ?, status = 'booked' WHERE plot_id = ?

customer.selectByPhone = SELECT * FROM customer WHERE contact_number = ?

project.selectAll = SELECT * FROM project

