spring.application.name=REES-6

# user queries


user.existsByEmail = SELECT COUNT(*) FROM users WHERE email = ?
user.existsByPhone = SELECT COUNT(*) FROM users WHERE phone = ?
user.insert = INSERT INTO users (user_id, email, password, name, phone, role, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
user.findByEmail = SELECT * FROM users WHERE email = ?
user.updatePassword = UPDATE users SET password = ? WHERE user_id = ?
UPDATE_PASSWORD=UPDATE User SET password = ? WHERE email = ?


#plot queries
plotinquirer.insert = INSERT INTO plot_inquirer (phone_number, name, address, created_at) VALUES (?, ?, ?, ?)

# SQL query to save a new project into the database
i# Project-related queries
project.selectAll=SELECT * FROM Project;
project.selectById=SELECT * FROM Project WHERE project_id = ?;
project.insert=INSERT INTO Project (project_name, survey_number, location, total_area, saleable_area, project_type, project_status, map_pdf) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
project.update=UPDATE Project SET project_name = ?, survey_number = ?, location = ?, total_area = ?, saleable_area = ?, project_type = ?, project_status = ?, map_pdf = ? WHERE project_id = ?;


plot.selectAll=SELECT * FROM Plot;

# Customer Queries
customer.insert=INSERT INTO customer (name, address, contact_number, aadhaar_number, pan_number, created_at) VALUES (?, ?, ?, ?, ?, NOW())
customer.selectByPhone=SELECT * FROM customer WHERE contact_number = ?
customer.selectAll=SELECT * FROM customer ORDER BY created_at DESC
